homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize  

http:
# base_url: !secret http_base_url
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 10.0.0.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
  
frontend:
panel_iframe:
  router:
    title: 'Router'
    icon: 'mdi:router-wireless'
    url: 'http://10.0.0.1'
  
group: !include_dir_merge_named group
discovery:
updater:
sun:
# history:

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.garadget_small_status
      - sensor.garadget_large_status
      - sensor.garadget_small_time_in_state
      - sensor.garadget_large_time_in_state
      - sensor.garadget_large_wifi_signal_strength
      - sensor.garadget_small_wifi_signal_strength
      - sensor.garadget_small_reflection_rate
      - sensor.garadget_large_reflection_rate
      - group.garage_doors
      - sensor.time
      - sensor.date
#logger:
#  default: info
recorder:
  purge_days: 7

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: jarvis.gddnet.io
  username: !secret MQTT_username
  password: !secret MQTT_password

insteon_local:
  host: 10.0.0.132
  username: !secret insteonuser
  password: !secret insteonpass
  timeout: 10
  port: 25105
  
zwave:
 usb_path: /dev/ttyACM0
  
tts:
  - platform: google
    language: 'en-us'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
light: !include_dir_merge_list light
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
