homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize

http:
# base_url: !secret http_base_url
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 10.0.0.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:
  javascript_version: latest
panel_iframe:
  router:
    title: 'Router'
    icon: 'mdi:router-wireless'
    url: 'https://10.0.0.1:8081'
config:
discovery:
updater:
sun:
# history:

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - group.garage_doors
      - sensor.time
      - sensor.date
logger:
  default: info
recorder:
  purge_interval: 30
  purge_keep_days: 7

mqtt:
  broker: jarvis.gddnet.com
  port: 1883
  client_id: jarvis
  keepalive: 60
  username: !secret MQTT_username
  password: !secret MQTT_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - zbayne

insteon_local:
  host: 10.0.0.132
  username: !secret insteonuser
  password: !secret insteonpass
  timeout: 10
  port: 25105
hue:
  bridges:
    - host: 10.0.0.75
      filename: phue.conf
group: !include groups.yaml

media_player:
  - platform: plex
  - platform: roku
  - platform: cast


zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 30000
  device_config:
    switch.ge_12722_onoff_relay_switch_switch:
      polling_intensity: 1
    switch.ge_12722_onoff_relay_switch_switch_2:
      polling_intensity: 1

tts:
  - platform: google
    language: 'en-us'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

zoneminder:
  host: camera.ipa.gddnet.com
  username: !secret zmuser
  password: !secret zmpass

camera:
  - platform: zoneminder

sensor: !include_dir_merge_list sensor
automation: !include automations.yaml
switch: !include_dir_merge_list switch
light: !include_dir_merge_list light
# Controls
input_select: !include input-selects.yaml
#input_slider: !include input-sliders.yaml
input_boolean: !include input-boolean.yaml
script: !include_dir_merge_named scripts/
zone: !include zones.yaml


notify:
  - name: zbayne
    platform: pushover
    api_key: !secret pushoverzbayne
    user_key: !secret pushoveruserkey
