alias: "Turn off laundry lights timer after movement"
trigger:
  - platform: state
    entity_id: sensor.laundrymove
    state: 'off'
    for:
      minutes: 1
action:
  - service: homeassistant.turn_off
    entity_id: switch.ge_12722_onoff_relay_switch_switch_3_0

