alias: "Turn On laundry light when there is movement"
trigger:
  - platform: state
    entity_id: sensor.laundrymove
    state: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: switch.ge_12722_onoff_relay_switch_switch_3_0

