automation:
  alias: Turn on Laundry lights when there is movement
  trigger:
    - platform: state
      entity_id: sensor.laundrymotion
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.laundrytimer

script:
  timed_lamp:
    alias: "Turn on lamp and set timer"
    sequence:
      # Cancel ev. old timers
      - execute_service: script.turn_off
        service_data:
           entity_id: script.timer_off
      - execute_service: light.turn_on
        service_data:
          entity_id: light.kitchen
      # Set new timer
      - execute_service: script.turn_on
        service_data:
          entity_id: script.timer_off

  timer_off:
    alias: "Turn off lamp after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - execute_service: light.turn_off
        service_data:
          entity_id: light.kitchen1
