alias: "Turn on kitchen light when there is movement"
trigger:
  - platform: state
    entity_id: group.all_devices
    state: 'home'
action:
  - service: homeassistant.turn_on
    entity_id: light.hue_white_lamp_3
