alias: "Turn on kitchen light when there is"
trigger:
  - platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0001_sensor_5_0
    state: 'off'
    for:
      minutes: 1
action:
  - service: homeassistant.turn_off
    entity_id: switch.ge_12722_onoff_relay_switch_switch_3_0
